/** @jsxImportSource theme-ui */
import Head from 'next/head'

import Header from './Header'
import Footer from './Footer'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Perma Pics</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        sx={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100%',
          backgroundColor: 'background',
        }}
      >
        <Header />
        <main
          sx={{
            width: '100%',
            flex: '1 1 auto',
            bg: 'inherit',
          }}
        >
          {children}
        </main>
        <Footer />
      </div>
    </>
  )
}
